---
abstract: 'Async Perl extension for UPnP'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.44, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Async-UPnP
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Encode: '0'
  HTTP::Request: '0'
  HTTP::Response: '0'
  IO::Async::Socket: '0'
  List::Util: '0'
  Moo: '2'
  MooX::Role::EventEmitter: '0.01'
  Net::Address::IP::Local: '0'
  Net::Async::HTTP: '0'
  Net::Async::HTTP::Server: '0'
  PerlX::Maybe: '0'
  Scalar::Util: '0'
  Try::Tiny: '0'
  URI: '0'
  XML::LibXML: '1.17'
  perl: '5.020'
resources:
  bugtracker: https://github.com/Corion/Net-Async-UPnP/issues
  license: https://dev.perl.org/licenses/
  repository: git://github.com/Corion/Net-Async-UPnP.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
